server:
  port: 10010
spring:
  application:
    name: j-gateway
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: admin
        instance:
          prefer-ip: true
  main:
    allow-bean-definition-overriding: true    #允许注册到eureka的名字和项目名一致
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    oauth:
      path: /api/**
      serviceId: j-auth
    user:
      path: /api/**
      serviceId: j-user
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
eureka:
  client:
    registryFetchIntervalSeconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      health-check-url-path: /actuator/health #admin 健康监测
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  connetTimeout: 500
  readTimeout: 5000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS