server:
  port: 10010
spring:
  application:
    name: j-gateway
  # 允许注册到eureka的名字和项目名一致
  main:
    allow-bean-definition-overriding: true
  # 设置admin监控中心配置
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: admin
        instance:
          prefer-ip: true
  # 设置zipkin+sleuth链路追踪配置
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 # 该值介于0.0到1.0之间，1.0则表示全部采集

# zuul网关的核心配置
zuul:
  ignored-services: '*'
  sensitiveHeaders:
  routes:
    oauth:
      path: /api-o/**
      serviceId: j-auth
    user:
      path: /api-u/**
      serviceId: j-user
    log:
      path: /api-l/**
      serviceId: j-log
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
  strip-prefix: true

#服务注册相关配置
eureka:
  client:
    registryFetchIntervalSeconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      health-check-url-path: /actuator/health #admin 健康监测
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  connetTimeout: 500
  readTimeout: 5000

# 监控相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"   # 配置启用所有的监控端点
  endpoint:
    health:
      show-details: ALWAYS # 显示详情, 该值除了always之外还有when-authorized、never，默认值是never。