server:
  port: 8002
spring:
  application:
    name: j-user
  datasource:
    url: jdbc:mysql://localhost:3306/jj?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.yx.user.pojo
  mapper-locations: classpath:/mybatis/*
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#调用access_token时必须加上此配置,从网关层访问认证服务器的user-me接口获取当前登录用户信息
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:10010/user-me
      prefer-token-info: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"