server:
  port: 10012
spring:
  application:
    name: j-user
  boot:
    admin:
      client:
        url: http://localhost:10000
        username: admin
        password: admin
        instance:
          prefer-ip: true
  main:
    allow-bean-definition-overriding: true    #允许注册到eureka的名字和项目名一致
  datasource:
    url: jdbc:mysql://localhost:3306/jj?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis-plus:
  typeAliasesPackage: com.yx.user.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个也是打印sql语句的
eureka:
  client:
    registryFetchIntervalSeconds: 5 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    health-check-url-path: /actuator/health #admin 健康监测
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#调用access_token时必须加上此配置,从网关层访问认证服务器的user-me接口获取当前登录用户信息
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:10011/user-me #先直接访问认证服务器的，回头改成网关的地址
      prefer-token-info: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
#      cors:
#        allowed-origins: "*"
#        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS
#打印sql语句
logging:
  level:
    com.yx.user.mapper: DEBUG